### ISSUE TITLE
Could this repository really be an alternative to distrochooser?

### ISSUE THREAD

**Issue by ghost** [flyingcakes85/distrochooser-but-better#5]

**Comment by flyingcakes85** [comment]
Hi. Thanks for your interest.

This repository is meant to be a joke since day 1. See this thread on EndeavourOS forum for reference: https://forum.endeavouros.com/t/distrochooser-but-better/15022?u=flyingcakes

Making this website useful is totally contrary to the reason why I wrote this.

If you wish to contribute, here's 2 things you could do:
1. Contribute to the **real** Distrochooser (highly recommended)
    - Repository: https://github.com/distrochooser/distrochooser
    - Website: https://distrochooser.de/
2. Fork either the real Distrochooser repo or my repo and make it as per your vision. Both repositories are under an open source license that allow you to fork and modify.

Coming to the the suggestions you've given.

> Look at this scenario. I have no knowledge of Linux, so I go to the website and fill in the information I can or can. From there, the site generates a custom script so that I can download or install Linux.

1. For a new user, I'll absolutely never suggest downloading random scripts from the internet and executing them.
2. Since the said script will (probably?) write an ISO image to a flash drive, it'll need superuser privileges. Again, I'll never ask anyone to trust such scripts even if I am the one to write them. All you need are 2 lines of code to download and flash an ISO.
```sh
wget https://website.com/static/distro.iso
sudo dd if=distro.iso of=/dev/sdd bs=1M
```
3. What will be custom? You'll build custom distro images in the cloud?

> Also, the repository says something like this: "A rewrite of distrochooser, but with significant improvements to its AI and Blockchain system."

Because my website is a joke and its mocking developers who throw in fancy trending tech into every hello world app they build. There is no AI or Blockchain in my website. Its literally just a static site.

> (In addition to the website, one may prefer some algorithm to facilitate the installation or download of the Linux distro. )

Why would you need an "algorithm" to download a distro? `wget` is all you need. You can try it. Beware, it'll use ~1GB data.

```sh
wget https://mirroronet.pl/pub/mirrors/archlinux/iso/2024.04.01/archlinux-2024.04.01-x86_64.iso
```

> What I propose is a significant improvement in the experience of installing Linux for the beginner or end user of Linux, which is in accordance with the description in the repository.

You should be approaching developers of a real distribution for this. My repository is just a static site.

> I can also create a custom installer for this

Approach a real distribution.

> Why can't we have a personalized Linux installation guide?

We can absolutely have it, but not in this repository. You're free to fork this repo and/or create your own repo for the purpose.

> Why can't we extend this repository for larger use cases?

Because the use case of this website, i.e. wasting user's time and always recommending EndeavourOS is already fulfilled.

> Does what I said make sense?

I appreciate your long text, but sadly, it doesn't make sense in the context of this repository.

Cheers,
flyingcakes
